# Настройки сайта
# Доступны через Liquid-теги site.title и т.д.
title: rustycrate.ru
email: rustycrate@michaelpankov.com
description: > # это позволяет отключить переводы строк до начала "baseurl:"
  Неофициальный русскоязычный сайт о языке программирования Rust
# Здесь переводы строк можно делать с помощью <br/>
baseurl: "" # путь до сайта от корня, напр. /blog/. В нашем случае сайт прямо в корне
set: "master"
url: "https://rustycrate.ru" # базовое имя хоста и протокол
# Эти параметры могут использоваться темой для Jekyll, чтобы поставить ссылки на профили
twitter_username:
github_username:  rust-lang-ru

# Настройки по умолчанию для определённых полей front matter
defaults:
  -
    scope:
      path: "" # пустая строка означает "все файлы в проекте"
      type: "posts" # эти настройки влияют на публикации
    values:
      layout: "post-deprecated" # шаблон по умолчанию
      comments: true # включены ли комментарии
      excerpt_separator: <!--cut-->

# Настройки сборки
# эти файлы и директории будут исключены из обработки Jekyll
exclude: [vendor, Gemfile, Gemfile.lock, travis.trash.id_rsa.enc, node_modules]
markdown: kramdown

kramdown:
  transliterated_header_ids: true

  syntax_highlighter: rouge

  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

gems:
  - jekyll-assets
  - jekyll-paginate-v2
  - mini_magick

pagination:
  enabled: true
  per_page: 5
  permalink: '/page:num/'
  title: ':title - страница :num из :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2
